config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Root page
  root 'users#show'

  # Login and signup
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resource :users

  # User accounts
  get 'users/:id' => 'users#show', as: :user

  # Subjects
  get 'subjects' => 'subjects#index'
  get 'subjects/:id' => 'subjects#show', as: :subject
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/associate.rb
class Associate < ApplicationRecord
  belongs_to :user
  belongs_to :friend
end

app/models/friend.rb
class Friend < ApplicationRecord
  has_one :associate
  has_one :user, through: :associate
end

app/models/lesson_time.rb
class LessonTime < ApplicationRecord
  belongs_to :subject_instance
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :subject_instance
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_one :user
end

app/models/subject_instance.rb
class SubjectInstance < ApplicationRecord
  has_many :teachers
  has_many :locations
  has_many :lesson_times
  has_one :subject

  belongs_to :user
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :subject_instance
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :associates
  has_many :friends, through: :associates
  has_many :subject_instances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  # Used for getting the current user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # Used to prohibit access to logged in users
  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_username(params[:session][:username])
    if @user && user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: %i[index show destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id # Create new session
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  def show
    @user = current_user
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetable Sharer</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.3.2/css/mdb.min.css" type="text/css">-->
  <script src="https://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-year-calendar/1.1.1/css/bootstrap-year-calendar.min.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-year-calendar/1.1.1/js/bootstrap-year-calendar.min.js"></script>
</head>

<body>
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsable">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand">Timetable Sharer</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapsable">
      <ul class="nav navbar-nav foo" id="menu">
        <li><a href="/">Home</a></li>
        <li><a href="#">A button</a></li>
        <li>
          <a href="/contact">Contact Us!</a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Stuff <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li class="dropdown-header">Great stuff!</li>
            <li><a href="/one">One</a></li>
            <li><a href="/two">Two</a></li>
            <li><a href="/three">Three</a></li>
            <li class="divider"></li>
            <li><a href="/admin">Admin Dashboard</a></li>
            <li><a href="/admin/users">Users</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right" align="right">
        <% if current_user %>
          <li class="navbar-text"><%= "Hello, #{current_user.username}" %></li>
          <li><%= link_to 'Profile', user_path(current_user) %></li>
          <li><%= link_to 'Log out', logout_path, method: 'delete' %></li>
        <% else %>
          <li><%= link_to 'Login', 'login' %></a></li>
          <li><%= link_to 'Sign up', 'signup' %></a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div id="main-container" class="container">
  <div class="row">
    <div class="col-md-12">
      <%= yield %>
    </div>
  </div>
</div>
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.3.2/js/mdb.min.js"></script>-->
</body>
</html>

app/views/users/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>Sign Up</h1>
  <%= bootstrap_form_for(@user) do |f| %>
    <%= f.text_field :first_name %>
    <%= f.text_field :last_name %>
    <%= f.text_field :username %>
    <%= f.password_field :password %>
    <%= f.submit "Sign Up" %>
  <% end %>
</div>